"""
Django settings for hotel_resilience project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wq)c6-)%l&fv%tq#2km@nm*7!63avr5+t9@8*8g$2-2y2(s4s%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel_resilience.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_resilience.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Brazzaville'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'core.User'

JAZZMIN_SETTINGS = {
    "site_title": "Hôtel La Résilience",
    "site_header": "Administration",
    "site_brand": "La Résilience",
    "welcome_sign": "Bienvenue dans l'espace de gestion",
    "copyright": "Acme Ltd - Hôtel La Résilience",
    "search_model": "core.Client",
    "topmenu_links": [
        {"name": "Dashboard", "url": "dashboard", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],
    "order_with_respect_to": [
        "core.Reservation",
        "core.Room",
        "core.Client",
        "core.Invoice",
        "auth.User",
    ],
    "icons": {
        "core.User": "fas fa-users-cog",
        "core.Room": "fas fa-bed",
        "core.Client": "fas fa-user-tie",
        "core.Reservation": "fas fa-calendar-check",
        "core.Invoice": "fas fa-file-invoice-dollar",
        "core.Payment": "fas fa-money-bill-wave",
    },
    "user_avatar": "profile_photo",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "sidebar": "sidebar-light-navy",
    "navbar": "navbar-navy navbar-dark",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# Email Configuration
# Pour le développement : les emails s'affichent dans la console
# Pour la production : configurez un vrai serveur SMTP
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Dev: console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Prod: SMTP
# EMAIL_HOST = 'smtp.gmail.com'  # Exemple pour Gmail
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre-mot-de-passe'
# DEFAULT_FROM_EMAIL = 'noreply@hotel-resilience.com'

# Authentication Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'