# Generated by Django 6.0.1 on 2026-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Téléphone')),
                ('id_document', models.CharField(max_length=50, verbose_name="Pièce d'identité")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numéro de chambre')),
                ('category', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOUBLE', 'Double'), ('SUITE', 'Suite')], max_length=10, verbose_name='Catégorie')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('status', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPEE', 'Occupée'), ('RESERVEE', 'Réservée'), ('MAINTENANCE', 'Maintenance')], default='LIBRE', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['number'],
            },
        ),
    ]
