# Generated by Django 6.0.1 on 2026-01-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Émise le')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('PARTIELLE', 'Partielle')], default='IMPAYEE', max_length=20, verbose_name='Statut')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
